repo: 'horizontal-nav'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing
  - body-margin-0
  - google-fonts
  - nav-hover

html:
  - path: 'index.html'
    has:
      - ['link[href*="Bevan"]', 'The Google Font, `Bevan`, is missing']
      - 'header'
      - 'header h1'
      - 'header nav'
      - 'header nav ul'
      - 'header nav ul li a'
    search:
      - 'Planets'
      - 'Introduction'
      - 'Terrestrial planets'
      - 'Mars'
      - 'Venus'

css:
  - path: 'css/main.css'
    has:
      - ['h1', 'font-family', 'Bevan, serif']
    search:
      - 'margin'
      - 'padding'
      - 'background-color'
      - 'list-style-type'
      - 'display'
      - 'inline-block'
      - 'border'
      - 'border-radius'
      - '#79756f'
      - '#595652'
      - '#713837'
      - '#f33'

screenshots:
  - path: 'index.html'
    sizes: [400, 650]
